Vagrant.configure("2") do |config|
  config.vm.box = "molflow/uworker-xenial"
  config.ssh.username = "molflow"
  config.ssh.password = "molflow"
  config.vm.provider :virtualbox do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end
  config.vm.synced_folder "../../src/", "/app"
  config.vm.synced_folder "../../", "/src"
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
