webapi:
  image: odinsmr/microq:latest
  ports:
    - 5000:5000
  environment:
    - USERVICE_DATABASE_URI=mysql+pymysql://testuser:secret@mysqlhost/smr
    - USERVICE_ADMIN_USER=admin
    - USERVICE_ADMIN_PASSWORD=sqrrl
  links:
    - mysqlhost

mysqlhost:
  image: docker2.molflow.com/devops/hermod_mysql
  environment:
    - MYSQL_ROOT_PASSWORD=empty
    - MYSQL_DATABASE=smr
    - MYSQL_USER=testuser
    - MYSQL_PASSWORD=secret
  ports:
    - 127.0.0.1:3306:3306
